name: REPLACE_TEMPLATE_VARIABLES
on:
  workflow_dispatch: # Allows manual trigger with user input
    inputs:
      custom_prefix:
        description: "Enter the component prefix to use"
        required: true
        default: "default_component_prefix"
      custom_id:
        description: "Enter the component ID to use"
        required: true
        default: "default_component_id"

permissions:
  contents: write

jobs:
  replace-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Validate Inputs
      - name: Validate Inputs
        run: |
          PREFIX=${{ inputs.custom_prefix }}
          ID=${{ inputs.custom_id }}

          # Regular expressions for validation
          REGEX="^[a-zA-Z][a-zA-Z0-9]*$"

          # Validate component_prefix
          if [[ ! "$PREFIX" =~ $REGEX ]]; then
            echo "Error: component_prefix must be alphanumeric, start with a letter, and contain no special characters."
            exit 1
          fi

          # Validate component_id
          if [[ ! "$ID" =~ $REGEX ]]; then
            echo "Error: component_id must be alphanumeric, start with a letter, and contain no special characters."
            exit 1
          fi

          echo "Validated Inputs: PREFIX=$PREFIX, ID=$ID"

      # Step 3: Rename directories, files, and update content
      - name: Rename directories, files, and update content
        run: |
          # Fetch validated inputs
          PREFIX=${{ inputs.custom_prefix }}
          ID=${{ inputs.custom_id }}

          echo "Using PREFIX=$PREFIX and ID=$ID"

          find . -type f ! -name 'replace_template_vars.yml' -exec sed -i 's/{{component_id}}/$ID/g' {} \;
          find . -type f ! -name 'replace_template_vars.yml' -exec sed -i 's/{{component_prefix}}/$PREFIX/g' {} \;

          # Rename files and directories with variables
          find . -depth -name '*{{component_id}}*' -execdir bash -c 'mv "$1" "${1//{\{\component_id\}\}/$ID}"' _ {} \;
          find . -depth -name '*{{component_prefix}}*' -execdir bash -c 'mv "$1" "${1//\{\{component_prefix\}\}/$PREFIX}"' _ {} \;

      - name: Clear and Rebuid Git Index
        run: |
          echo "Clearing Git index"
          rm -f .git/index
          git reset
      
      # Step 4: Commit changes
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Replaced Template Variables"
          git push